ALEMBIC_REVISION = '9bb6f1128279'

TIME_FOR_WAITING_PING = 1  # minutes

TIME_FACTOR_TO_FIX_STATUS = 5

PAUSE_FOR_CYCLE_MAIN_WORKER = 15  # seconds


PAUSE_FOR_CYCLE_ROSEMARY = 2  # seconds

TIME_FOR_DELETE_OLD_WORKER = 12  # hours

